[package]
name = "battlesnake"
version = "0.0.1"
authors = ["Miroslav Andrysek <miroslav@andrysek.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
